# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install tsx for running TypeScript files directly
RUN npm install -g tsx

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of the source code
COPY . .

# Expose no ports since this server communicates over STDIO

# Default command to start the MCP server
CMD ["tsx", "serverMCP.ts"]
